[Bugfix] NeighborPriorityQueue panics, when it is at capacity and NaN distance is inserted (#796)
# Why
When the inserted distance is not comparable with existing distances
(neither larger nor smaller), the `insert_idx` is incorrectly calculated
(it is set to self.size). This typically happens when inserting a
neighbor with NaN distance.

This causes NeighborPriorityQueue to panic with this error, when the
queue is already full:
```
thread 'main' panicked at src\index\neighbor\neighbor_priority_queue.rs:125:26:
insertion index (is 65) should be <= len (is 64)
```

End-to-end repro: see
`vectors_with_large_values_should_be_inserted_and_searched_without_panic()`
test in `diskann_async.rs`.

# What
This PR changes the behavior of NeighborPriorityQueue to ignore an
incomparable value (NaN or similar) when the queue is full and we can't
determine where it belongs in the sorted order.

Note: the alternative approach would be to insert a NaN value at the end
of the queue, but it would overwrite legit non-NaN value, which is not
desirable.

The bug was discovered when we encountered large, non‑normalized vectors
in a random dataset used during one of our experiments.

---------

Co-authored-by: Alex Razumov (from Dev Box) <alrazu@microsoft.com>