Properly feature-gate `diskann-benchmark` (#1245)
This is a follow-up to #1242 to move `diskann-benchmark` to the new
feature gated feature.

A summary of the updated error messages is shown below:

# When trying to load `bf-tree` inputs

**Command**
```
cargo run --package diskann-benchmark -- \
    run \
    --input-file ./diskann-benchmark/example/graph-index-bftree-stream.json \
    --output-file temp.json
```
**Before**
```
Error: while processing input 1 of 1

Caused by:
    Unrecognized input tag: "graph-index-stream-bftree-full-precision"
```
**After**
```
Error: while processing input 1 of 1

Caused by:
    use of the "graph-index-stream-bftree-full-precision" input is gated behind the feature "bftree"
```

# When trying to run a gated benchmark
**Command**
```
cargo run --package diskann-benchmark -- \
    run \
    --input-file ./diskann-benchmark/example/graph-index-spherical-quantization.json \
    --output-file temp.json
```
**Before**
```
...
Closest matches:

    1. "graph-index-spherical-quantization":
        - Requires the "spherical-quantization" feature

    2. "spherical-exhaustive-search":
        - expected tag "exhaustive-spherical-quantization" - instead got "graph-index-build-spherical-quantization"

    3. "minmax-exhaustive-search":
        - expected tag "exhaustive-minmax-quantization" - instead got "graph-index-build-spherical-quantization"


Error: could not find a benchmark for all inputs
```
**After**
```
No active benchmarks are registered for tag "graph-index-build-spherical-quantization"

Found 1 gated benchmark matching this input:

    * "graph-index-spherical-quantization" (requires the feature "spherical-quantization")

Error: could not find a benchmark for all inputs
```

# Input Discovery
When running `cargo run --package diskann-benchmark -- inputs --all`,
the following is now displayed
```
Available input kinds are listed below:
    disk-index
    exhaustive-minmax-quantization
    exhaustive-product-quantization
    exhaustive-spherical-quantization
    flat-search
    graph-index-build
    graph-index-build-pq
    graph-index-build-spherical-quantization
    graph-index-build-sq
    graph-index-dynamic-run
    metadata-index-build
    multi-vector-op
    graph-index-build-bftree-full-precision (requires the feature "bftree")
    graph-index-build-bftree-spherical-quantization (requires the feature "bftree")
    graph-index-stream-bftree-full-precision (requires the feature "bftree")
    graph-index-stream-bftree-spherical-quantization (requires the feature "bftree")
```